node:
  build: .
  ports:
    - "99:99"
  volumes:
    - ./files:/container/files
    - ./public:/container/public
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  environment:
    - ADMIN_USER=test
    - ADMIN_PASSWORD=test